# 05 - Model Registry and Deployment (SageMaker SDK v3)

Registers the model produced by notebook 04, deploys a real-time endpoint with data capture, invokes it, and runs batch transform.

This version uses explicit SageMaker control-plane APIs for model creation and registration plus the v3 `sagemaker.core.transformer.Transformer`. It avoids the unstable repack implementation in early `ModelBuilder` v3 releases and contains no SDK v2 imports.

In [1]:
import sys, json, time, os, shutil, tempfile, tarfile
from pathlib import Path

# Run this notebook from <repository>/notebooks.
REPO_ROOT = Path.cwd().resolve().parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import boto3
import joblib
import numpy as np
import pandas as pd
import scipy
import sklearn
import awswrangler as wr
from botocore.exceptions import ClientError

from sagemaker.core.helper.session_helper import Session, get_execution_role
from sagemaker.core import image_uris
from src import config, data_utils, features, modeling

session = Session()
role = get_execution_role()
REGION = session.boto_region_name
BUCKET = os.environ.get("CHURN_BUCKET", session.default_bucket())

sm = boto3.client("sagemaker", region_name=REGION)
s3 = boto3.client("s3", region_name=REGION)
runtime = boto3.client("sagemaker-runtime", region_name=REGION)

FRAMEWORK_VERSION = "1.4-2-py312"
INSTANCE_TYPE = "ml.m5.large"

def stage_source():
    build = Path(tempfile.mkdtemp(prefix="churn-inference-"))
    shutil.copytree(REPO_ROOT / "src", build / "src", ignore=shutil.ignore_patterns("__pycache__"))
    for script in (REPO_ROOT / "scripts").glob("*.py"):
        shutil.copy2(script, build / script.name)
    # Match the environment that created model.joblib. Unpinned packages can
    # upgrade scikit-learn/NumPy inside the endpoint and make the pickle unloadable.
    (build / "requirements.txt").write_text(
        f"numpy=={np.__version__}\n"
        f"scipy=={scipy.__version__}\n"
        f"pandas=={pd.__version__}\n"
        f"scikit-learn=={sklearn.__version__}\n"
        f"joblib=={joblib.__version__}\n"
    )
    # The Python 3.12 sklearn container's auto-generated setup.py can omit a
    # standalone inference.py from the wheel. Declare it explicitly.
    (build / "setup.py").write_text(
        "from setuptools import find_packages, setup\n"
        "setup(name='churn-inference', version='1.0.0', "
        "py_modules=['inference'], packages=find_packages(), "
        f"install_requires=['numpy=={np.__version__}', 'scipy=={scipy.__version__}', "
        f"'pandas=={pd.__version__}', 'scikit-learn=={sklearn.__version__}', "
        f"'joblib=={joblib.__version__}'])\n"
    )
    # The training artifact produced by notebook 04 may pickle the BitGenerator
    # class rather than its name. Apply the same compatibility shim used there
    # before model_fn calls joblib.load during the endpoint health check.
    with (build / "inference.py").open("a") as inference_file:
        inference_file.write(
            "\n# NumPy model-artifact compatibility shim\n"
            "from numpy.random import MT19937, PCG64, Philox, SFC64\n"
            "import numpy.random._pickle as _numpy_pickle\n"
            "for _bit_generator in (MT19937, PCG64, Philox, SFC64):\n"
            "    _numpy_pickle.BitGenerators.setdefault(_bit_generator, _bit_generator)\n"
        )
    return str(build)

latest_key = f"{config.MODEL_PREFIX}/latest/latest.json"

def load_or_recover_manifest():
    try:
        return json.loads(s3.get_object(Bucket=BUCKET, Key=latest_key)["Body"].read())
    except s3.exceptions.NoSuchKey:
        print(f"s3://{BUCKET}/{latest_key} is missing; recovering the newest completed churn training job")

    jobs = sm.list_training_jobs(
        NameContains="churn-train", StatusEquals="Completed",
        SortBy="CreationTime", SortOrder="Descending", MaxResults=20,
    )["TrainingJobSummaries"]
    if not jobs:
        raise RuntimeError(
            "No completed 'churn-train' job was found. Run section 8 of notebook 04 first, "
            "then rerun this cell."
        )

    job = sm.describe_training_job(TrainingJobName=jobs[0]["TrainingJobName"])
    recovered = {
        "model_data": job["ModelArtifacts"]["S3ModelArtifacts"],
        "model_type": job.get("HyperParameters", {}).get("model-type", "unknown").strip('"'),
        # Used only by Model Monitor. The deployed model retains its own trained threshold.
        "threshold": 0.5,
        "training_job_name": job["TrainingJobName"],
        "recovered": True,
    }
    evaluation_key = f"{config.MODEL_PREFIX}/latest/evaluation.json"
    try:
        s3.head_object(Bucket=BUCKET, Key=evaluation_key)
        recovered["evaluation"] = f"s3://{BUCKET}/{evaluation_key}"
    except Exception as error:
        if getattr(error, "response", {}).get("Error", {}).get("Code") not in ("404", "NoSuchKey", "NotFound"):
            raise
        print("evaluation.json is also missing; registration will continue without model metrics")

    # Repair the manifest so notebooks 05 and 06 use the same recovered artifact.
    s3.put_object(Bucket=BUCKET, Key=latest_key, Body=json.dumps(recovered, indent=2).encode())
    return recovered

latest = load_or_recover_manifest()
print("SDK v3 session:", REGION, BUCKET)
latest

from sagemaker.core.transformer import Transformer

sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: /home/sagemaker-user/.config/sagemaker/config.yaml
SDK v3 session: us-east-1 sagemaker-us-east-1-025824828736

## 1. Build and register the model

The code explicitly repacks `inference.py` and the project package into the trained artifact. This avoids the broken temporary-directory behavior in early SDK v3 `ModelBuilder` releases. The framework version intentionally matches notebook 04.

In [2]:
try:
    group = sm.describe_model_package_group(ModelPackageGroupName=config.MODEL_PACKAGE_GROUP)
    print("model package group already exists:", group["ModelPackageGroupArn"])
except ClientError as error:
    code = error.response.get("Error", {}).get("Code")
    message = error.response.get("Error", {}).get("Message", "")
    if code not in ("ValidationException", "ResourceNotFound") and "does not exist" not in message.lower():
        raise
    group = sm.create_model_package_group(
        ModelPackageGroupName=config.MODEL_PACKAGE_GROUP,
        ModelPackageGroupDescription="Customer churn classifier",
    )
    print("created model package group:", group["ModelPackageGroupArn"])

image_uri = image_uris.retrieve(
    framework="sklearn", region=REGION, version=FRAMEWORK_VERSION,
    py_version="py3", instance_type=INSTANCE_TYPE, image_scope="inference",
)
source_dir = stage_source()

def repack_model(model_data, source_directory):
    work = Path(tempfile.mkdtemp(prefix="churn-repack-"))
    original = work / "original-model.tar.gz"
    extracted = work / "model"
    extracted.mkdir()

    bucket, key = model_data[5:].split("/", 1)
    s3.download_file(bucket, key, str(original))
    with tarfile.open(original, "r:gz") as archive:
        archive.extractall(extracted, filter="data")

    code_dir = extracted / "code"
    code_dir.mkdir(exist_ok=True)
    for item in Path(source_directory).iterdir():
        destination = code_dir / item.name
        if item.is_dir():
            shutil.copytree(item, destination, dirs_exist_ok=True)
        else:
            shutil.copy2(item, destination)

    if not (code_dir / "inference.py").is_file():
        raise RuntimeError("Repacked artifact is missing code/inference.py")

    repacked = work / "repacked-model.tar.gz"
    with tarfile.open(repacked, "w:gz") as archive:
        for item in extracted.iterdir():
            archive.add(item, arcname=item.name)

    key = f"{config.MODEL_PREFIX}/repacked/{int(time.time())}/model.tar.gz"
    s3.upload_file(str(repacked), BUCKET, key)
    return f"s3://{BUCKET}/{key}"

repacked_model_data = repack_model(latest["model_data"], source_dir)
timestamp = time.strftime("%Y%m%d-%H%M%S")
model_name = f"churn-model-{timestamp}"
container = {
    "Image": image_uri,
    "ModelDataUrl": repacked_model_data,
    "Environment": {
        "SAGEMAKER_PROGRAM": "inference.py",
        # The model archive is extracted under /opt/ml/model. Point script mode
        # at its code subdirectory; do not use the S3 model URI here.
        "SAGEMAKER_SUBMIT_DIRECTORY": "/opt/ml/model/code",
        "SAGEMAKER_CONTAINER_LOG_LEVEL": "20",
        "SAGEMAKER_REGION": REGION,
    },
}

sm.create_model(ModelName=model_name, PrimaryContainer=container, ExecutionRoleArn=role)

package_request = {
    "ModelPackageGroupName": config.MODEL_PACKAGE_GROUP,
    "ModelPackageDescription": f"{latest['model_type']} churn model, threshold {latest['threshold']}",
    "ModelApprovalStatus": "Approved",
    "InferenceSpecification": {
        "Containers": [container],
        "SupportedContentTypes": ["text/csv"],
        "SupportedResponseMIMETypes": ["text/csv"],
        "SupportedRealtimeInferenceInstanceTypes": [INSTANCE_TYPE],
        "SupportedTransformInstanceTypes": [INSTANCE_TYPE],
    },
}
if latest.get("evaluation"):
    package_request["ModelMetrics"] = {
        "ModelQuality": {
            "Statistics": {"ContentType": "application/json", "S3Uri": latest["evaluation"]}
        }
    }
package = sm.create_model_package(**package_request)
print("registered:", package["ModelPackageArn"])
print("SageMaker model:", model_name)
print("repacked artifact:", repacked_model_data)

model package group already exists: arn:aws:sagemaker:us-east-1:025824828736:model-package-group/churn-model-group
registered: arn:aws:sagemaker:us-east-1:025824828736:model-package/churn-model-group/6
SageMaker model: churn-model-20261019-121409
repacked artifact: s3://sagemaker-us-east-1-025824828736/churn/models/repacked/1792412049/model.tar.gz

## 2. Deploy or update the real-time endpoint

The endpoint captures every request and response for notebook 06. Re-running this cell updates an existing endpoint.

In [3]:
endpoint_config_name = f"{config.ENDPOINT_NAME}-{time.strftime('%Y%m%d-%H%M%S')}"
sm.create_endpoint_config(
    EndpointConfigName=endpoint_config_name,
    ProductionVariants=[{
        "VariantName": "AllTraffic",
        "ModelName": model_name,
        "InitialInstanceCount": 1,
        "InstanceType": INSTANCE_TYPE,
        "InitialVariantWeight": 1.0,
    }],
    DataCaptureConfig={
        "EnableCapture": True,
        "InitialSamplingPercentage": 100,
        "DestinationS3Uri": f"s3://{BUCKET}/{config.MONITOR_PREFIX}/data-capture",
        "CaptureOptions": [{"CaptureMode": "Input"}, {"CaptureMode": "Output"}],
        "CaptureContentTypeHeader": {"CsvContentTypes": ["text/csv"]},
    },
)

try:
    endpoint_description = sm.describe_endpoint(EndpointName=config.ENDPOINT_NAME)
except ClientError as error:
    if error.response.get("Error", {}).get("Code") != "ValidationException":
        raise
    endpoint_description = None

if endpoint_description is None:
    sm.create_endpoint(EndpointName=config.ENDPOINT_NAME, EndpointConfigName=endpoint_config_name)
    print("creating endpoint")
else:
    status = endpoint_description["EndpointStatus"]
    print("existing endpoint status:", status)
    if status == "InService":
        sm.update_endpoint(EndpointName=config.ENDPOINT_NAME, EndpointConfigName=endpoint_config_name)
        print("updating endpoint")
    elif status in ("Creating", "Updating", "SystemUpdating", "RollingBack"):
        print("endpoint operation already in progress; waiting without submitting another update")
    elif status in ("Failed", "OutOfService", "UpdateRollbackFailed"):
        reason = endpoint_description.get("FailureReason", "No failure reason returned")
        raise RuntimeError(
            f"Endpoint is {status}: {reason}\n"
            "AWS cannot update a failed endpoint. Preserve this reason, then delete the endpoint "
            "and rerun this cell only after correcting the underlying container/configuration error."
        )
    else:
        raise RuntimeError(f"Endpoint is in unsupported state {status}: {endpoint_description}")

sm.get_waiter("endpoint_in_service").wait(
    EndpointName=config.ENDPOINT_NAME,
    WaiterConfig={"Delay": 30, "MaxAttempts": 120},
)
print("endpoint ready:", config.ENDPOINT_NAME)

creating endpoint
endpoint ready: churn-endpoint

## 3. Invoke the endpoint

In [4]:
production = data_utils.load_processed("production")

def invoke(rows: pd.DataFrame, inference_ids=None):
    out = []
    lines = rows[features.MODEL_FEATURES].to_csv(header=False, index=False).strip().split("\n")
    for i, line in enumerate(lines):
        kwargs = {"InferenceId": str(inference_ids[i])} if inference_ids is not None else {}
        response = runtime.invoke_endpoint(
            EndpointName=config.ENDPOINT_NAME, ContentType="text/csv", Accept="text/csv",
            Body=line.encode(), **kwargs,
        )
        out.append(response["Body"].read().decode().strip().split(","))
    return pd.DataFrame(out, columns=["probability", "prediction", "risk_tier"]).astype(
        {"probability": float, "prediction": int}
    )

sample = production.head(5)
pd.concat([sample[["customer_id", "churn"]].reset_index(drop=True), invoke(sample)], axis=1)

[10/19/26 12:23:14] INFO     Initializing a Ray instance                                               ]8;id=7440671;file:///opt/conda/lib/python3.12/site-packages/awswrangler/distributed/ray/_core.py\_core.py]8;;\:]8;id=7440672;file:///opt/conda/lib/python3.12/site-packages/awswrangler/distributed/ray/_core.py#202\202]8;;\

2026-10-19 12:23:16,418	WARNING services.py:2213 -- WARNING: The object store is using /tmp/ray instead of /dev/shm because /dev/shm has only 906964992 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=2.16gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.
2026-10-19 12:23:18,598	INFO worker.py:2012 -- Started a local Ray instance.
/opt/conda/lib/python3.12/site-packages/ray/_private/worker.py:2051: FutureWarning: Tip: In future versions of Ray, Ray will no longer override accelerator visible devices env var if num_gpus=0 or num_gpus=None (default). To enable this behavior and turn off this error message, set RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO=0
  warnings.warn(

   customer_id  churn  probability  prediction risk_tier
0            1      1     1.000000           1      high
1            2      0     1.000000           1      high
2            3      0     0.999981           1      high
3            4      0     0.999999           1      high
4            5      0     0.999999           1      high

## 4. Batch transform

In [5]:
input_path = f"s3://{BUCKET}/churn/batch-input/production_features.csv"
output_path = f"s3://{BUCKET}/churn/batch-output/raw"
wr.s3.to_csv(production[features.MODEL_FEATURES], path=input_path, header=False, index=False)

transformer = Transformer(
    model_name=model_name,
    instance_count=1,
    instance_type=INSTANCE_TYPE,
    output_path=output_path,
    accept="text/csv",
    assemble_with="Line",
    strategy="MultiRecord",
    max_payload=6,
    sagemaker_session=session,
)
transformer.transform(data=input_path, content_type="text/csv", split_type="Line", wait=True, logs=True)

[10/19/26 12:23:27] INFO     Creating transform job with name:                                   ]8;id=7440679;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/transformer.py\transformer.py]8;;\:]8;id=7440680;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/transformer.py#403\403]8;;\
                             churn-model-20261019-121409-2026-10-19-12-23-27-296

Output()

[10/19/26 12:26:59] INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440687;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440688;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026-10-19 12:26:51,445 INFO - sagemaker-containers - No GPUs
                             detected (normal if no gpus installed)

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440693;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440694;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026-10-19 12:26:51,447 INFO - sagemaker-containers - No GPUs
                             detected (normal if no gpus installed)

[10/19/26 12:27:00] INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440699;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440700;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026-10-19 12:26:51,448 INFO - sagemaker-containers - nginx config:

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440705;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440706;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             worker_processes auto;

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440711;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440712;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             daemon off;

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440717;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440718;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             pid /tmp/nginx.pid;

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440723;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440724;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             error_log  /dev/stderr;

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440729;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440730;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             worker_rlimit_nofile 4096;

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440735;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440736;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             events {
                               worker_connections 2048;

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440741;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440742;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             }

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440747;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440748;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             http {
                               include /etc/nginx/mime.types;
                               default_type application/octet-stream;
                               access_log /dev/stdout combined;
                               upstream gunicorn {
                                 server unix:/tmp/gunicorn.sock;
                               }
                               server {
                                 listen 8080 deferred;
                                 client_max_body_size 0;
                                 keepalive_timeout 3;
                                 location ~ ^/(ping|invocations|execution-parameters) {
                                   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                                   proxy_set_header Host $http_host;
                                   proxy_redirect off;
                                   proxy_read_timeout 60s;
                                   proxy_pass http://gunicorn;
                                 }
                                 location / {
                                   return 404 "{}";
                                 }
                               }

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440753;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440754;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             }

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440759;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440760;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026-10-19 12:26:51,462 INFO - sagemaker-containers - Installing
                             module with the following command:

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440765;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440766;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             /usr/bin/python -m pip install . -r requirements.txt

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440771;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440772;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             Processing ./.
                               Installing build dependencies: started

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440777;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440778;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                               Installing build dependencies: finished with status 'done'
                               Getting requirements to build wheel: started

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440783;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440784;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                               Getting requirements to build wheel: finished with status 'done'
                               Preparing metadata (pyproject.toml): started
                               Preparing metadata (pyproject.toml): finished with status 'done'

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440789;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440790;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             Collecting numpy==1.26.4 (from -r requirements.txt (line 1))
                               Downloading
                             numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64
                             .whl.metadata (61 kB)

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440795;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440796;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             Collecting scipy==1.16.3 (from -r requirements.txt (line 2))
                               Downloading
                             scipy-1.16.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64
                             .whl.metadata (62 kB)

[10/19/26 12:27:05] INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440801;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440802;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             Collecting pandas==2.3.3 (from -r requirements.txt (line 3))
                               Downloading
                             pandas-2.3.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_6
                             4.whl.metadata (91 kB)

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440807;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440808;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             Collecting scikit-learn==1.7.2 (from -r requirements.txt (line 4))
                               Downloading
                             scikit_learn-1.7.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_
                             x86_64.whl.metadata (11 kB)

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440813;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440814;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             Requirement already satisfied: joblib==1.6.0 in
                             /usr/local/lib/python3.12/dist-packages (from -r requirements.txt
                             (line 5)) (1.6.0)

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440819;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440820;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             Requirement already satisfied: python-dateutil>=2.8.2 in
                             /usr/local/lib/python3.12/dist-packages (from pandas==2.3.3->-r
                             requirements.txt (line 3)) (2.9.0.post0)

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440825;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440826;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             Requirement already satisfied: pytz>=2020.1 in
                             /usr/local/lib/python3.12/dist-packages (from pandas==2.3.3->-r
                             requirements.txt (line 3)) (2026.5)

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440831;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440832;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             Requirement already satisfied: tzdata>=2022.7 in
                             /usr/local/lib/python3.12/dist-packages (from pandas==2.3.3->-r
                             requirements.txt (line 3)) (2026.5)

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440837;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440838;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             Requirement already satisfied: threadpoolctl>=3.1.0 in
                             /usr/local/lib/python3.12/dist-packages (from
                             scikit-learn==1.7.2->-r requirements.txt (line 4)) (3.7.0)

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440843;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440844;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             Requirement already satisfied: cloudpickle>=3.0 in
                             /usr/local/lib/python3.12/dist-packages (from joblib==1.6.0->-r
                             requirements.txt (line 5)) (3.1.2)

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440849;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440850;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             Requirement already satisfied: six>=1.5 in
                             /usr/local/lib/python3.12/dist-packages (from
                             python-dateutil>=2.8.2->pandas==2.3.3->-r requirements.txt (line
                             3)) (1.16.0)

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440855;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440856;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             Downloading
                             numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64
                             .whl (18.0 MB)
                                ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 85.9 MB/s
                             0:00:00

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440861;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440862;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             Downloading
                             scipy-1.16.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64
                             .whl (35.7 MB)

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440867;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440868;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                                ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.7/35.7 MB 97.0 MB/s
                             0:00:00

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440873;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440874;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             Downloading
                             pandas-2.3.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_6
                             4.whl (12.4 MB)
                                ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 143.0 MB/s
                             0:00:00

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440879;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440880;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             Downloading
                             scikit_learn-1.7.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_
                             x86_64.whl (9.5 MB)
                                ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 140.8 MB/s
                             0:00:00

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440885;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440886;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             Building wheels for collected packages: churn-inference
                               Building wheel for churn-inference (pyproject.toml): started

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440891;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440892;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                               Building wheel for churn-inference (pyproject.toml): finished
                             with status 'done'
                               Created wheel for churn-inference:
                             filename=churn_inference-1.0.0-py3-none-any.whl size=11553
                             sha256=ce515b1cb1f202a294f324c60806a869322eb4d59f5bbf82b7a20cc698aa
                             dddf
                               Stored in directory:
                             /home/model-server/tmp/pip-ephem-wheel-cache-ohfx5m0o/wheels/6e/f2/
                             4a/da972bde801c4b516b25757b9156b5d85fe41e8b907f1e3a0e

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440897;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440898;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             Successfully built churn-inference

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440903;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440904;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             Installing collected packages: numpy, scipy, pandas, scikit-learn,
                             churn-inference
                               Attempting uninstall: numpy
                                 Found existing installation: numpy 2.1.0
                                 Uninstalling numpy-2.1.0:
                                   Successfully uninstalled numpy-2.1.0

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440909;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440910;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:26:59 [crit] 13#13: *1 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440915;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440916;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:26:59 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440921;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440922;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:26:59 [crit] 14#14: *3 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440927;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440928;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:26:59 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440933;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440934;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:26:59 [crit] 13#13: *5 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440939;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440940;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:26:59 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440945;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440946;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:26:59 [crit] 13#13: *7 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440951;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440952;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:26:59 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440957;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440958;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:26:59 [crit] 13#13: *9 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440963;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440964;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:26:59 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440969;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440970;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:26:59 [crit] 13#13: *11 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440975;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440976;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:26:59 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440981;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440982;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:00 [crit] 13#13: *13 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440987;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440988;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:00 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440993;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7440994;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:00 [crit] 13#13: *15 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7440999;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441000;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:00 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441005;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441006;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:00 [crit] 13#13: *17 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441011;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441012;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:00 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441017;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441018;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:00 [crit] 13#13: *19 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441023;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441024;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:00 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441029;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441030;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:00 [crit] 13#13: *21 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441035;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441036;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:00 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441041;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441042;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:00 [crit] 13#13: *23 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

[10/19/26 12:27:10] INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441065;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441066;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:00 [crit] 13#13: *27 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441071;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441072;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:00 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441077;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441078;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:00 [crit] 13#13: *29 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441083;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441084;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:00 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441089;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441090;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:00 [crit] 13#13: *31 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441095;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441096;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:00 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441101;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441102;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:01 [crit] 13#13: *33 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441107;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441108;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:01 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441113;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441114;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:01 [crit] 13#13: *35 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441119;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441120;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:01 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441125;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441126;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:01 [crit] 14#14: *37 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441131;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441132;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:01 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"
                               Attempting uninstall: scipy
                                 Found existing installation: scipy 1.18.1

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441137;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441138;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:01 [crit] 14#14: *39 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441143;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441144;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:01 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"
                                 Uninstalling scipy-1.18.1:

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441149;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441150;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:01 [crit] 14#14: *41 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441155;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441156;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:01 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441161;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441162;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:01 [crit] 14#14: *43 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441167;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441168;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:01 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"
                                   Successfully uninstalled scipy-1.18.1

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441173;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441174;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:01 [crit] 14#14: *45 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441179;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441180;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:01 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441185;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441186;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:01 [crit] 14#14: *47 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441191;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441192;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:01 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441197;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441198;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:01 [crit] 14#14: *49 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441203;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441204;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:01 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441209;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441210;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:02 [crit] 14#14: *51 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441215;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441216;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:02 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441221;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441222;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:02 [crit] 14#14: *53 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441227;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441228;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:02 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441233;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441234;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:02 [crit] 14#14: *55 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441239;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441240;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:02 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441245;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441246;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:02 [crit] 14#14: *57 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441263;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441264;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:02 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441269;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441270;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:02 [crit] 14#14: *61 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441275;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441276;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:02 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441281;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441282;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:02 [crit] 14#14: *63 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441287;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441288;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:02 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441293;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441294;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:02 [crit] 14#14: *65 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441299;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441300;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:02 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441305;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441306;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:02 [crit] 14#14: *67 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441311;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441312;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:02 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441317;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441318;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:02 [crit] 13#13: *69 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441323;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441324;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:02 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441329;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441330;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:03 [crit] 13#13: *71 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441335;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441336;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:03 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441341;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441342;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:03 [crit] 13#13: *73 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441347;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441348;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:03 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441353;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441354;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:03 [crit] 13#13: *75 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441359;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441360;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:03 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441365;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441366;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:03 [crit] 13#13: *77 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441371;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441372;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:03 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441377;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441378;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:03 [crit] 13#13: *79 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441383;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441384;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:03 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441389;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441390;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:03 [crit] 13#13: *81 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441395;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441396;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:03 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441401;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441402;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:03 [crit] 13#13: *83 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441407;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441408;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:03 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441413;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441414;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:03 [crit] 13#13: *85 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441419;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441420;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:03 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441425;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441426;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:03 [crit] 13#13: *87 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441431;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441432;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:03 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441437;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441438;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:04 [crit] 13#13: *89 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441443;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441444;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:04 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441449;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441450;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:04 [crit] 13#13: *91 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441455;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441456;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:04 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441461;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441462;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:04 [crit] 13#13: *93 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441467;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441468;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:04 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441473;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441474;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:04 [crit] 13#13: *95 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441479;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441480;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:04 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441485;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441486;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:04 [crit] 13#13: *97 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441491;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441492;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:04 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441497;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441498;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:04 [crit] 13#13: *99 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441503;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441504;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:04 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441509;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441510;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:04 [crit] 14#14: *101 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441515;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441516;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:04 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441521;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441522;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:04 [crit] 14#14: *103 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441527;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441528;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:04 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441533;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441534;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:04 [crit] 14#14: *105 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441539;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441540;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:04 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441545;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441546;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:04 [crit] 14#14: *107 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441551;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441552;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:04 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441557;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441558;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:05 [crit] 14#14: *109 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441563;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441564;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:05 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441569;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441570;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:05 [crit] 14#14: *111 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441575;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441576;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:05 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441581;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441582;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:05 [crit] 14#14: *113 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441587;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441588;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:05 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441593;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441594;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:05 [crit] 14#14: *115 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441599;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441600;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:05 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441605;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441606;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:05 [crit] 14#14: *117 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441611;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441612;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:05 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441617;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441618;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:05 [crit] 14#14: *119 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441623;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441624;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:05 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441629;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441630;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:05 [crit] 14#14: *121 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441635;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441636;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:05 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

[10/19/26 12:27:16] INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441641;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441642;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:05 [crit] 14#14: *123 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441647;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441648;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:05 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441653;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441654;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:05 [crit] 14#14: *125 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441659;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441660;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:05 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441665;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441666;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:06 [crit] 14#14: *127 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441671;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441672;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:06 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441677;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441678;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:06 [crit] 14#14: *129 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441683;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441684;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:06 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441689;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441690;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:06 [crit] 14#14: *131 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441695;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441696;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:06 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441701;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441702;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:06 [crit] 13#13: *133 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441707;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441708;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:06 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"
                               Attempting uninstall: pandas

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441713;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441714;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:06 [crit] 13#13: *135 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441719;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441720;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:06 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"
                                 Found existing installation: pandas 2.3.2
                                 Uninstalling pandas-2.3.2:

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441725;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441726;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:06 [crit] 13#13: *137 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441731;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441732;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:06 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441737;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441738;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:06 [crit] 13#13: *139 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441743;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441744;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:06 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441749;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441750;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                                   Successfully uninstalled pandas-2.3.2

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441755;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441756;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:06 [crit] 13#13: *141 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441761;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441762;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:06 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441767;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441768;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:06 [crit] 13#13: *143 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441773;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441774;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:06 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441779;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441780;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:06 [crit] 13#13: *145 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441785;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441786;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:06 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441791;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441792;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:07 [crit] 13#13: *147 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441797;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441798;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:07 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441803;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441804;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:07 [crit] 13#13: *149 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441809;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441810;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:07 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441815;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441816;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:07 [crit] 13#13: *151 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441821;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441822;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:07 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441827;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441828;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:07 [crit] 13#13: *153 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441833;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441834;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:07 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441839;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441840;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:07 [crit] 13#13: *155 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441845;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441846;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:07 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441851;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441852;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:07 [crit] 13#13: *157 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441857;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441858;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:07 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441863;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441864;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:07 [crit] 13#13: *159 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441869;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441870;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:07 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441875;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441876;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:07 [crit] 13#13: *161 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441881;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441882;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:07 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441887;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441888;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:07 [crit] 13#13: *163 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441893;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441894;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:07 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441899;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441900;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:08 [crit] 14#14: *165 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441905;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441906;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:08 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441911;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441912;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:08 [crit] 14#14: *167 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441917;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441918;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:08 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441923;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441924;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:08 [crit] 14#14: *169 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441929;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441930;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:08 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441935;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441936;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:08 [crit] 14#14: *171 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441941;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441942;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:08 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441947;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441948;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:08 [crit] 14#14: *173 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441953;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441954;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:08 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441959;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441960;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:08 [crit] 14#14: *175 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441965;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441966;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:08 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441971;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441972;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:08 [crit] 14#14: *177 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441977;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441978;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:08 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441983;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441984;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:08 [crit] 14#14: *179 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441989;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441990;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:08 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7441995;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7441996;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:08 [crit] 14#14: *181 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442001;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442002;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:08 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442007;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442008;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:08 [crit] 14#14: *183 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442013;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442014;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:08 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442019;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442020;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:09 [crit] 14#14: *185 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442025;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442026;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:09 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442031;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442032;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:09 [crit] 14#14: *187 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442037;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442038;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:09 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442043;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442044;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:09 [crit] 14#14: *189 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442049;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442050;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:09 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442055;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442056;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:09 [crit] 14#14: *191 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442061;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442062;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:09 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442067;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442068;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:09 [crit] 14#14: *193 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442073;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442074;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:09 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442079;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442080;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:09 [crit] 14#14: *195 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442085;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442086;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:09 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442091;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442092;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:09 [crit] 13#13: *197 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442097;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442098;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:09 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442103;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442104;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:09 [crit] 13#13: *199 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442109;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442110;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:09 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442115;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442116;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:09 [crit] 13#13: *201 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442121;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442122;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:09 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442127;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442128;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:10 [crit] 13#13: *203 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442133;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442134;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:10 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442139;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442140;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:10 [crit] 13#13: *205 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442151;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442152;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:10 [crit] 13#13: *207 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442157;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442158;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:10 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442163;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442164;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:10 [crit] 13#13: *209 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442169;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442170;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:10 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442175;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442176;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:10 [crit] 13#13: *211 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442181;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442182;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:10 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442187;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442188;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:10 [crit] 13#13: *213 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442193;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442194;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:10 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442199;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442200;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:10 [crit] 13#13: *215 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442205;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442206;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:10 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

[10/19/26 12:27:21] INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442211;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442212;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:10 [crit] 13#13: *217 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442217;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442218;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:10 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442223;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442224;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:10 [crit] 13#13: *219 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442229;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442230;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:10 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442235;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442236;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:10 [crit] 13#13: *221 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442241;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442242;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:10 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442247;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442248;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:11 [crit] 13#13: *223 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442253;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442254;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:11 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442259;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442260;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:11 [crit] 13#13: *225 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442265;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442266;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:11 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442271;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442272;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:11 [crit] 13#13: *227 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442277;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442278;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:11 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442289;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442290;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:11 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442295;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442296;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:11 [crit] 14#14: *231 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442301;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442302;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:11 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442307;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442308;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:11 [crit] 14#14: *233 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442313;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442314;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:11 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442319;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442320;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:11 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442325;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442326;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:11 [crit] 14#14: *235 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442331;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442332;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:11 [crit] 14#14: *237 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442337;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442338;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:11 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442343;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442344;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:11 [crit] 14#14: *239 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442349;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442350;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:11 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442355;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442356;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:12 [crit] 14#14: *241 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442361;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442362;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:12 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442367;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442368;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:12 [crit] 14#14: *243 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442373;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442374;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:12 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"
                               Attempting uninstall: scikit-learn
                                 Found existing installation: scikit-learn 1.4.2
                                 Uninstalling scikit-learn-1.4.2:

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442379;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442380;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:12 [crit] 14#14: *245 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442385;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442386;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:12 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"
                                   Successfully uninstalled scikit-learn-1.4.2

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442391;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442392;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:12 [crit] 14#14: *247 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442397;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442398;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:12 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442403;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442404;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:12 [crit] 14#14: *249 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442409;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442410;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:12 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442415;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442416;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:12 [crit] 14#14: *251 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442421;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442422;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:12 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442427;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442428;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:12 [crit] 14#14: *253 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442433;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442434;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:12 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442439;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442440;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:12 [crit] 14#14: *255 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442445;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442446;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:12 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442451;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442452;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:12 [crit] 14#14: *257 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442457;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442458;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:12 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442463;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442464;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:12 [crit] 14#14: *259 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442469;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442470;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:12 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442475;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442476;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:13 [crit] 13#13: *261 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442481;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442482;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:13 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442487;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442488;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:13 [crit] 13#13: *263 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442493;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442494;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:13 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442499;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442500;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:13 [crit] 13#13: *265 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442505;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442506;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:13 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442511;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442512;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:13 [crit] 13#13: *267 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442517;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442518;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:13 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442523;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442524;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:13 [crit] 13#13: *269 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442529;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442530;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:13 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442535;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442536;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:13 [crit] 13#13: *271 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442541;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442542;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:13 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442547;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442548;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:13 [crit] 13#13: *273 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442553;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442554;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:13 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442559;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442560;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:13 [crit] 13#13: *275 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442565;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442566;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:13 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442571;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442572;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:13 [crit] 13#13: *277 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442577;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442578;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:13 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442583;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442584;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:14 [crit] 13#13: *279 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442589;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442590;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:14 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442595;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442596;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:14 [crit] 13#13: *281 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442601;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442602;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:14 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442607;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442608;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:14 [crit] 13#13: *283 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442613;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442614;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:14 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442619;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442620;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:14 [crit] 13#13: *285 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442625;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442626;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:14 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442631;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442632;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:14 [crit] 13#13: *287 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442637;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442638;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:14 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442643;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442644;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:14 [crit] 13#13: *289 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442649;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442650;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:14 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442655;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442656;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:14 [crit] 13#13: *291 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442661;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442662;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:14 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442667;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442668;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:14 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442673;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442674;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:14 [crit] 14#14: *293 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442679;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442680;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             ERROR: pip's dependency resolver does not currently take into
                             account all the packages that are installed. This behaviour is the
                             source of the following dependency conflicts.

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442685;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442686;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             sagemaker-sklearn-container 2.0 requires multi-model-server==1.1.1,
                             but you have multi-model-server 1.1.2 which is incompatible.

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442691;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442692;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             sagemaker-sklearn-container 2.0 requires numpy==2.1.0, but you have
                             numpy 1.26.4 which is incompatible.

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442697;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442698;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             sagemaker-sklearn-container 2.0 requires pandas==2.3.2, but you
                             have pandas 2.3.3 which is incompatible.

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442703;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442704;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             sagemaker-sklearn-container 2.0 requires scikit-learn==1.4.2, but
                             you have scikit-learn 1.7.2 which is incompatible.

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442709;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442710;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             sagemaker-sklearn-container 2.0 requires setuptools==80.9.0, but
                             you have setuptools 83.0.0 which is incompatible.

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442715;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442716;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             sagemaker-sklearn-container 2.0 requires wheel==0.45.1, but you
                             have wheel 0.46.2 which is incompatible.

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442721;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442722;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             Successfully installed churn-inference-1.0.0 numpy-1.26.4
                             pandas-2.3.3 scikit-learn-1.7.2 scipy-1.16.3

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442727;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442728;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:14 [crit] 14#14: *295 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442733;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442734;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:14 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442739;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442740;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:14 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442745;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442746;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:14 [crit] 14#14: *297 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442751;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442752;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:15 [crit] 14#14: *299 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442757;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442758;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:15 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442763;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442764;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:15 [crit] 14#14: *301 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442769;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442770;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:15 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442775;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442776;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:15 [crit] 14#14: *303 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442787;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442788;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:15 [crit] 14#14: *305 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442793;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442794;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:15 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442799;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442800;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:15 [crit] 14#14: *307 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442805;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442806;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:15 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442811;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442812;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026/10/19 12:27:15 [crit] 14#14: *309 connect() to
                             unix:/tmp/gunicorn.sock failed (2: No such file or directory) while
                             connecting to upstream, client: 169.254.255.130, server: , request:
                             "GET /ping HTTP/1.1", upstream:
                             "http://unix:/tmp/gunicorn.sock:/ping", host:
                             "169.254.255.131:8080"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442817;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442818;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:15 +0000] "GET /ping
                             HTTP/1.1" 502 157 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442823;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442824;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             [2026-10-19 12:27:15 +0000] [59] [INFO] Starting gunicorn 23.0.0

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442829;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442830;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             [2026-10-19 12:27:15 +0000] [59] [INFO] Listening at:
                             unix:/tmp/gunicorn.sock (59)

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442835;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442836;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             [2026-10-19 12:27:15 +0000] [59] [INFO] Using worker: gevent

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442841;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442842;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             [2026-10-19 12:27:15 +0000] [60] [INFO] Booting worker with pid: 60

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442847;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442848;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             [2026-10-19 12:27:15 +0000] [61] [INFO] Booting worker with pid: 61

[10/19/26 12:27:27] INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442853;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442854;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             2026-10-19 12:27:18,560 INFO - sagemaker-containers - No GPUs
                             detected (normal if no gpus installed)

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442859;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442860;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:19 +0000] "GET /ping
                             HTTP/1.1" 200 0 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442865;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442866;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:19 +0000] "GET
                             /execution-parameters HTTP/1.1" 404 232 "-" "Go-http-client/1.1"

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442871;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442872;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             Exception ignored in: <function _after_fork at 0x7f34838a4c20>

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442877;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442878;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             Traceback (most recent call last):
                               File "/usr/lib/python3.12/threading.py", line 1691, in
                             _after_fork
                                 thread._set_tstate_lock()
                               File "/usr/lib/python3.12/threading.py", line 1051, in
                             _set_tstate_lock
                                 if not self.daemon:
                                        ^^^^^^^^^^^
                               File "/usr/lib/python3.12/threading.py", line 1246, in daemon
                                 assert self._initialized, "Thread.__init__() not called"
                                        ^^^^^^^^^^^^^^^^^

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442883;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442884;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             AssertionError: Thread.__init__() not called

                    INFO     churn-model-20261019-121409-2026-10-19-12-23-27-296/i-043549a62dd8e ]8;id=7442889;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442890;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32476\32476]8;;\
                             a94a-1792412746:
                             169.254.255.130 - - [19/Oct/2026:12:27:21 +0000] "POST /invocations
                             HTTP/1.1" 200 1028995 "-" "Go-http-client/1.1"

                    INFO     Final Resource Status: Completed                                    ]8;id=7442896;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=7442897;file:///opt/conda/lib/python3.12/site-packages/sagemaker/core/resources.py#32482\32482]8;;\

In [6]:
out = wr.s3.read_csv(
    f"{output_path}/production_features.csv.out", header=None,
    names=["probability", "prediction", "risk_tier"],
)
scored = pd.concat([production[["customer_id", "churn"]].reset_index(drop=True), out], axis=1)
wr.s3.to_csv(scored, path=f"s3://{BUCKET}/churn/batch-output/scored_customers.csv", index=False)

print(scored["risk_tier"].value_counts())
print({k: round(v, 4) for k, v in modeling.metrics(
    scored["churn"], scored["probability"], latest["threshold"]
).items() if k in ("roc_auc", "precision", "recall", "top_decile_precision")})
scored.sort_values("probability", ascending=False).head(10)

risk_tier
high      62879
low        1326
medium      169
Name: count, dtype: int64
{'roc_auc': 0.6916, 'precision': 0.4834, 'recall': 0.9993, 'top_decile_precision': 0.6256}

       customer_id  churn  probability  prediction risk_tier
64373        64374      1          1.0           1      high
0                1      1          1.0           1      high
1                2      0          1.0           1      high
64372        64373      1          1.0           1      high
64371        64372      1          1.0           1      high
64369        64370      1          1.0           1      high
5                6      0          1.0           1      high
6                7      1          1.0           1      high
7                8      0          1.0           1      high
8                9      0          1.0           1      high

## 5. Registry contents and cleanup

In [7]:
pkgs = sm.list_model_packages(
    ModelPackageGroupName=config.MODEL_PACKAGE_GROUP,
    SortBy="CreationTime", SortOrder="Descending",
)
pd.DataFrame(pkgs["ModelPackageSummaryList"])[
    ["ModelPackageVersion", "ModelApprovalStatus", "CreationTime", "ModelPackageArn"]
]

,ModelPackageVersion,ModelApprovalStatus,CreationTime,ModelPackageArn
0,6,Approved,2026-10-19 12:14:10.811000+00:00,arn:aws:sagemaker:us-east-1:025824828736:model...
1,5,Approved,2026-10-19 11:36:20.070000+00:00,arn:aws:sagemaker:us-east-1:025824828736:model...
2,4,Approved,2026-10-19 11:07:15.903000+00:00,arn:aws:sagemaker:us-east-1:025824828736:model...
3,3,Approved,2026-10-19 10:30:09.539000+00:00,arn:aws:sagemaker:us-east-1:025824828736:model...
4,2,Approved,2026-10-19 10:21:49.438000+00:00,arn:aws:sagemaker:us-east-1:025824828736:model...
5,1,Approved,2026-10-19 09:43:48.116000+00:00,arn:aws:sagemaker:us-east-1:025824828736:model...

To stop endpoint charges after the demo:

```python
sm.delete_endpoint(EndpointName=config.ENDPOINT_NAME)
```

Do not run that cleanup before notebook 06.

In [8]:
%%html

<p><b>Shutting down your kernel for this notebook to release resources.</b></p>
<button class="sm-command-button" data-commandlinker-command="kernelmenu:shutdown" style="display:none;">Shutdown Kernel</button>
        
<script>
try {
    els = document.getElementsByClassName("sm-command-button");
    els[0].click();
}
catch(err) {
    // NoOp
}    
</script>

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1792412920.020929   20210 chttp2_transport.cc:1182] ipv4:169.255.255.2:46105: Got goaway [2] err=UNAVAILABLE:GOAWAY received; Error code: 2; Debug Text: Cancelling all calls {created_time:"2026-10-19T12:28:40.020925552+00:00", http2_error:2, grpc_status:14}
*** SIGTERM received at time=1792412922 on cpu 1 ***
PC: @     0x7f363965f2d2  (unknown)  epoll_wait
[2026-10-19 12:28:42,499 E 19598 19598] logging.cc:474: *** SIGTERM received at time=1792412922 on cpu 1 ***
[2026-10-19 12:28:42,499 E 19598 19598] logging.cc:474: PC: @     0x7f363965f2d2  (unknown)  epoll_wait